### ISSUE TITLE
No npm library?

### ISSUE THREAD

**Issue by princefishthrower** [datatrans/secure-fields-sample#18]
Hi Datatrans team,

It would seem the only way to load this library is over the minified cdn link, is that correct?

Is there a reason this isn't distributed through npm?

Thank you for your time.

Chris

**Comment by pstadler** [comment]
These are samples on how to integrate secure fields. We're currently not planning on releasing libraries. The only source you should load is `https://pay.datatrans.com/upp/payment/js/secure-fields-2.0.0.min.js` for production and `https://pay.sandbox.datatrans.com/upp/payment/js/secure-fields-2.0.0.min.js` for sandbox. Please refer to our docs: https://docs.datatrans.ch/docs/secure-fields
