### ISSUE TITLE
Input field triggers blur event on focus on ios safari and chrome

### ISSUE THREAD

**Issue by Mhmdabed11** [datatrans/secure-fields-sample#20]
Hey guys :) I am using your react example in my project and I am putting it inside a [Formik](https://formik.org/docs/api/formik) component. On IOS safari and chrome, whenever I click the CC field, the field loses focus and immediately emits a blur event. I have to click on the field around 3 times to make it focus. I cannot show a reproduction of the issue as it is internal code. Do you guys have any idea why would this happen ?

**Comment by pstadler** [comment]
Hi Mohammad

Could you share some of your code with us? Unfortunately, we're unable to reproduce it.

**Comment by dmengelt** [comment]
@Mhmdabed11 or maybe try to create a small reproducer without "internal code".
Also, I guess you are not able to reproduce the issue with [our example](https://datatrans.github.io/secure-fields-sample/). Right?

**Comment by dmengelt** [comment]
@Mhmdabed11 any update from your side?

**Comment by Mhmdabed11** [comment]
Hey @dmengelt , thanks for following up. I was unable to reproduce the issue with your example. After some investigation,  what was happening is that whenever I focus on the CVV or CC fields, the page scrolls a bit to put the field in focus which is expected. Once the scroll happens, then the keyboard automatically closes and the fields (CVV and CC) trigger the blur event. One workaround for me was to stop the scroll propagation to the SecureFields in the `Securefields.js` file. That made things work as expected.

**Comment by Mhmdabed11** [comment]
I did not get the time to create a small reproducer from my end, but I will do so early next week 👍

**Comment by dmengelt** [comment]
@Mhmdabed11 awesome. lets us know!
